{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sonarqube-plugins.serviceAccountName" . }}
  labels:
{{ include "sonarqube-plugins.labels" . | nindent 4 }}
{{- end -}}
